orders:
  commission:
    - name: initcommission
      image: lsstsqre/inituserhome
      securityContext:
        runAsUser: 0
        runAsNonRootUser: false
      volumeMounts:
        - mountPath: /homedirs
          name: homedirs
  volumes:
    - name: homedirs
      emptyDir: {}

  # TODO/fixme!!!! - this has to match homedir config for nublado2     
  #volumes:
  #  - name: homedirs
  #    nfs:
  #      server: 192.41.122.33 #todo_kn
  #      path: /jhome #todo_kn
