vault-secrets-operator:
  environmentVars:
    - name: VAULT_TOKEN
      valueFrom:
        secretKeyRef:
          name: vault-secrets-operator
          key: VAULT_TOKEN
    - name: VAULT_TOKEN_LEASE_DURATION
      valueFrom:
        secretKeyRef:
          name: vault-secrets-operator
          key: VAULT_TOKEN_LEASE_DURATION
  vault:
    address: "http://vault.vault:8200"
    reconciliationTime: 60
