{{- if (index .Values "ingress-nginx" "enabled") -}}
apiVersion: v1
kind: Namespace
metadata:
  name: rsp-ingress-nginx # TF
spec:
  finalizers:
    - kubernetes
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: rsp-ingress-nginx # TF
    server: https://kubernetes.default.svc
  project: default
  source:
    path: applications/ingress-nginx
    repoURL: {{ .Values.repoURL }}
    targetRevision: {{ .Values.targetRevision }}
    helm:
      parameters:
        - name: "global.vaultSecretsPath"
          value: {{ .Values.vaultPathPrefix | quote }}
      valueFiles:
        - "values.yaml"
        - "values-{{ .Values.environment }}.yaml"
{{- end -}}
