ingress-nginx:
  controller:
    config:
      large-client-header-buffers: "4 64k"
      proxy-buffer-size: "64k"
      use-proxy-protocol: "false"
      enable-health-monitor: "false"
    #servce:
    #  loadBalancerIP: "192.41.122.16" #todo_kn
    #  annotations:
    #    kubernetes.io/ingress.class: "openstack"
    #    loadbalancer.openstack.org/enable-health-monitor: "false"

    # note: this is a namespace/secret path. If you use global namespace
    #       prefix, set it in here
    extraArgs:
      default-ssl-certificate: rsp-ingress-nginx/ingress-certificate
vaultCertificate:
  enabled: true
