argo-cd:
  redis:
    serviceAccount:
        create: true
        name: redis

  controller:
    args:
      repoServerTimeoutSeconds: "180"

  server:
    ingress:
      hosts:
        - "argocd2.cis.gov.pl"


  openshift:
     enabled: true
