argo-cd:
  redis:
    serviceAccount:
      create: true
      name: redis
  configs:
    cm:
      url: "https://rsp2.cis.gov.pl/argo-cd"
  server:
    ingress:
      hostname: "rsp2.cis.gov.pl"
      tls: false
  openshift:
    enabled: true
