controller:
  config:
    images:
      source:
        type: "docker"
        registry: "registry.hub.docker.com"
        repository: "lsstsqre/sciplat-lab"
    lab:
      namespaceAnnotations:
        'openshift.io/sa.scc.mcs': '"s0:c0"'
        'openshift.io/sa.scc.uid-range': '"{{uid}}/1"'
        'openshift.io/sa.scc.supplemental-groups': '"{{gid}}/1"'
      #initContainers:
      #  - name: "inithome"
      #    image:
      #      repository: "ghcr.io/lsst-sqre/nublado-inithome"
      #      tag: "8.9.2"
      #    privileged: true
      #    volumeMounts:
      #      - containerPath: "/home"
      #        volumeName: "home"
      #env: # TODO pgpass/buttler
      pullSecret: "pull-secret"
      volumes:
        - name: "data"
          source:
            serverPath: "/cloud/production/okdpoz2/lsst/data"
            server: "10.60.1.215"
            type: "nfs"
        - name: "home"
          source:
            serverPath: "/cloud/production/okdpoz2/lsst/home"
            server: "10.60.1.215"
            type: "nfs"
      volumeMounts:
        - containerPath: "/home"
          volumeName: "home"
        - containerPath: "/data"
          volumeName: "data"

proxy:
  ingress:
    annotations:
      nginx.ingress.kubernetes.io/proxy-connect-timeout: "50s"
      nginx.ingress.kubernetes.io/proxy-read-timeout: "50s"
      nginx.ingress.kubernetes.io/client-max-body-size: "50m"
hub:
  internalDatabase: true
jupyterhub:
  hub:
    db:
      upgrade: true
