redis:
  persistence:
    enabled: false
config:
  internalDatabase: true
  oidcServer:
    enabled: false
  updateSchema: true # note: set it to false after bootstrap
  #github:
  #  clientId: "1f936200994f9792ea82"
  oidc:
    clientId: "rsp"
    audience: "rsp"
    loginUrl: "https://rsp.cis.gov.pl/keycloak/realms/rsp/protocol/openid-connect/auth"
    tokenUrl: "https://rsp.cis.gov.pl/keycloak/realms/rsp/protocol/openid-connect/token"
    issuer: "https://rsp.cis.gov.pl/keycloak/realms/rsp"
    scopes:
      - "openid"
    usernameClaim: "preferred_username"

  ldap:
    url: "ldap://ldap:10389"
    userDn: "cn=admin,dc=ncbj,dc=gov"
    userBaseDn: "ou=people,dc=ncbj,dc=gov"
    uidAttr: "uidNumber"
    gidAttr: "gidNumber"
    groupBaseDn: "cn=groups,dc=ncbj,dc=gov"


  initialAdmins:
    - "fruboes"
    - "tfruboes"
    - "knawro"
  groupMapping:
  #  "admin:token":
  #  "write:sasquatch":
    "exec:admin":
      - github:
          organization: "lsst-pl"
          team: "admin"
    "exec:internal-tools":
      - github:
          organization: "lsst-pl"
          team: "admin"
      - github:
          organization: "lsst-pl"
          team: "ncbj"
    "exec:notebook":
      - github:
          organization: "lsst-pl"
          team: "admin"
      - github:
          organization: "lsst-pl"
          team: "ncbj"
    "exec:portal":
      - github:
          organization: "lsst-pl"
          team: "admin"
      - github:
          organization: "lsst-pl"
          team: "ncbj"
    "read:image":
      - github:
          organization: "lsst-pl"
          team: "admin"
      - github:
          organization: "lsst-pl"
          team: "ncbj"
    "read:tap":
      - github:
          organization: "lsst-pl"
          team: "admin"
      - github:
          organization: "lsst-pl"
          team: "ncbj"
