redis:
  persistence:
    enabled: false

config:
  databaseUrl: "postgresql://gafaelfawr@postgres.postgres/gafaelfawr"

  oidcServer: ## temp./fixme XXX
    enabled: false

  #github:
  #  clientId: "64d11db34c968448381e" # FIXME


  # https://gafaelfawr.lsst.io/dev/internals/gafaelfawr.config.OIDCConfig.html
  oidc:
    clientId: "53dcc7ed261ab3137c1153ecc5bf8c632b172d27e29ee343ba79187832e16063"
    loginUrl: "https://code.cis.gov.pl/oauth/authorize"
    tokenUrl: "https://code.cis.gov.pl/oauth/token"
    scopes:
       - "openid"
       - "profile"
       - "read_user"
    issuer: "https://code.cis.gov.pl"
    gidClaim: "sub"
    uidClaim: "sub"
    groupsClaim: "groups_direct"
    #usernameClaim: "nickname"
    usernameClaim: "sub_legacy" # see https://gitlab.com/gitlab-org/gitlab/-/merge_requests/110922

  initialAdmins:
    - "71ed25ae7c690b0cba764a442410d55a5c5be7a52f6788b118735235c1062351"
    - "8646951cffac794fe9e3ff53b8ad6884e88bb709d22e5f0ff9600b8e7b902fe6"

  groupMapping:
    "admin:token": "lssttest"
    "user:token": "lssttest"
    "exec:admin": "lssttest"
    "read:all":
      - "lssttest"
    "exec:internal-tools":
      - "lssttest"
    "exec:notebook":
      - "lssttest"
    "exec:portal":
      - "lssttest"
    "read:tap":
      - "lssttest"
    "read:image":
      - "lssttest"





  # Allow access by GitHub team.
  #  groupMapping:
  #    "exec:admin":
  #      - github:
  #          organization: "lsp-pl"
  #          team: "dev"
  #    "exec:notebook":
  #      - github:
  #          organization: "lsp-pl"
  #          team: "dev"
  #    "exec:internal-tools":
  #      - github:
  #          organization: "lsp-pl"
  #          team: "dev"
  #    "exec:portal":
  #      - github:
  #          organization: "lsp-pl"
  #          team: "dev"
  #    "exec:user":
  #      - github:
  #          organization: "lsp-pl"
  #          team: "dev"
  #    "read:workspace":
  #      - github:
  #          organization: "lsp-pl"
  #          team: "dev"
  #    "read:workspace/user":
  #      - github:
  #          organization: "lsp-pl"
  #          team: "dev"
  #    "write:workspace/user":
  #      - github:
  #          organization: "lsp-pl"
  #          team: "dev"
  #    "read:image":
  #      - github:
  #          organization: "lsp-pl"
  #          team: "dev"
  #    "read:tap":
  #      - github:
  #          organization: "lsp-pl"
  #          team: "dev"
  #
