redis:
  persistence:
    enabled: false
config:
  internalDatabase: true
  oidcServer:
    enabled: false
  updateSchema: true # note: set it to false after bootstrap
  #github:
  #  clientId: "1f936200994f9792ea82"
  oidc:
    clientId: "rsp"
    audience: "rsp"
    loginUrl: "https://rsp.cis.gov.pl/keycloak/realms/rsp/protocol/openid-connect/auth"
    tokenUrl: "https://rsp.cis.gov.pl/keycloak/realms/rsp/protocol/openid-connect/token"
    issuer: "https://rsp.cis.gov.pl/keycloak/realms/rsp"
    scopes:
      - "openid"
    usernameClaim: "preferred_username"

  ldap:
    url: "ldap://ldap.ldap-test.svc.cluster.local:10389"
    userDn: "cn=admin,dc=ncbj,dc=gov"
    userBaseDn: "ou=people,dc=ncbj,dc=gov"
    uidAttr: "uidNumber"
    gidAttr: "gidNumber"
    groupBaseDn: "ou=groups,dc=ncbj,dc=gov"

  initialAdmins:
    - "fruboes"
    - "tfruboes"
    - "knawro"

  groupMapping:
    "admin:token":
      - "rsp_admins"
    "admin:jupyterlab":
      - "rsp_admins"
    "exec:admin":
      - "rsp_admins"
    "exec:internal-tools":
      - "rsp_users"
    "exec:notebook":
      - "rsp_users"
    "exec:portal":
      - "rsp_users"
    "read:image":
      - "rsp_users"
    "read:tap":
      - "rsp_users"
    "write:files":
      - "rsp_users"
    "user:token":
      - "rsp_users"
