redis:
  persistence:
    enabled: false

config:
  databaseUrl: "postgresql://gafaelfawr@postgres.postgres/gafaelfawr"

  oidcServer: ## temp./fixme XXX
    enabled: false

  #github:
  #  clientId: "64d11db34c968448381e" # FIXME


  oidc:
    clientId: "53dcc7ed261ab3137c1153ecc5bf8c632b172d27e29ee343ba79187832e16063"
    loginUrl: "https://code.cis.gov.pl/oauth/authorize"
    tokenUrl: "https://code.cis.gov.pl/oauth/token"
    # scopes:
    #   - "openid"
    issuer: "https://code.cis.gov.pl"
    gidClaim: "gid_number"
    uidClaim: "uid_number"
    groupsClaim: "groups"
    usernameClaim: "preferred_username"



  # Allow access by GitHub team.
  groupMapping:
    "exec:admin":
      - github:
          organization: "lsp-pl"
          team: "dev"
    "exec:notebook":
      - github:
          organization: "lsp-pl"
          team: "dev"
    "exec:internal-tools":
      - github:
          organization: "lsp-pl"
          team: "dev"
    "exec:portal":
      - github:
          organization: "lsp-pl"
          team: "dev"
    "exec:user":
      - github:
          organization: "lsp-pl"
          team: "dev"
    "read:workspace":
      - github:
          organization: "lsp-pl"
          team: "dev"
    "read:workspace/user":
      - github:
          organization: "lsp-pl"
          team: "dev"
    "write:workspace/user":
      - github:
          organization: "lsp-pl"
          team: "dev"
    "read:image":
      - github:
          organization: "lsp-pl"
          team: "dev"
    "read:tap":
      - github:
          organization: "lsp-pl"
          team: "dev"

  initialAdmins:
    - "stvoutsin"
